server:
  port: 8000

spring:
  application:
    name: rbac-application-service
  datasource:
    url: jdbc:mysql://localhost:3306/appdemo
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

  mail:
    host: smtp.gmail.com
    port: 587
    username: virtusa.rbac@gmail.com
    password: fqeqopcnavnhmdjh
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
